#include <iostream>
#include <fstream>
#include <string>
#include <vector>
#include <sstream>
#include <algorithm>
#include <cmath>
#include <limits>
#include <iomanip>
#include <unordered_map>
#include <unordered_set>

// NOTE: This code was generated by AI for quick understanding.
// It is expected to evolve and will be subject to change in the future.

struct Point {
	double x = 0.0;
	double y = 0.0;
};

struct MidpointCandidate {
	Point p;
	double score = 0.0;
	int coneA = -1;
	int coneB = -1;
};

static double sqr(double v) {
	return v * v;
}

static double dist(const Point& a, const Point& b) {
	return std::sqrt(sqr(a.x - b.x) + sqr(a.y - b.y));
}

static Point operator+(const Point& a, const Point& b) {
	return {a.x + b.x, a.y + b.y};
}

static Point operator-(const Point& a, const Point& b) {
	return {a.x - b.x, a.y - b.y};
}

static Point operator*(const Point& a, double s) {
	return {a.x * s, a.y * s};
}

static Point operator/(const Point& a, double s) {
	return {a.x / s, a.y / s};
}

static double dot(const Point& a, const Point& b) {
	return a.x * b.x + a.y * b.y;
}

static double norm(const Point& a) {
	return std::sqrt(dot(a, a));
}

static Point normalize(const Point& a) {
	const double n = norm(a);
	if (n < 1e-9) {
		return {1.0, 0.0};
	}
	return a / n;
}

static double cross(const Point& a, const Point& b) {
	return a.x * b.y - a.y * b.x;
}

static double orientation(const Point& a, const Point& b, const Point& c) {
	return cross(b - a, c - a);
}

static bool onSegment(const Point& a, const Point& b, const Point& p) {
	return std::min(a.x, b.x) - 1e-9 <= p.x && p.x <= std::max(a.x, b.x) + 1e-9 &&
		   std::min(a.y, b.y) - 1e-9 <= p.y && p.y <= std::max(a.y, b.y) + 1e-9;
}

static bool segmentsIntersect(const Point& a, const Point& b, const Point& c, const Point& d) {
	const double o1 = orientation(a, b, c);
	const double o2 = orientation(a, b, d);
	const double o3 = orientation(c, d, a);
	const double o4 = orientation(c, d, b);

	const bool general = ((o1 > 0.0 && o2 < 0.0) || (o1 < 0.0 && o2 > 0.0)) &&
						 ((o3 > 0.0 && o4 < 0.0) || (o3 < 0.0 && o4 > 0.0));
	if (general) {
		return true;
	}

	if (std::abs(o1) < 1e-9 && onSegment(a, b, c)) return true;
	if (std::abs(o2) < 1e-9 && onSegment(a, b, d)) return true;
	if (std::abs(o3) < 1e-9 && onSegment(c, d, a)) return true;
	if (std::abs(o4) < 1e-9 && onSegment(c, d, b)) return true;
	return false;
}

static std::vector<Point> readCsv(const std::string& filePath) {
	std::ifstream in(filePath);
	if (!in.is_open()) {
		throw std::runtime_error("Failed to open input file: " + filePath);
	}

	std::vector<Point> points;
	std::string line;
	bool firstLine = true;

	while (std::getline(in, line)) {
		if (line.empty()) {
			continue;
		}

		if (firstLine) {
			firstLine = false;
			if (line.find("x") != std::string::npos && line.find("y") != std::string::npos) {
				continue;
			}
		}

		std::stringstream ss(line);
		std::string sx;
		std::string sy;
		if (!std::getline(ss, sx, ',')) {
			continue;
		}
		if (!std::getline(ss, sy, ',')) {
			continue;
		}

		try {
			points.push_back({std::stod(sx), std::stod(sy)});
		} catch (...) {
			continue;
		}
	}

	return points;
}

static void writeCsv(const std::string& filePath, const std::vector<Point>& points) {
	std::ofstream out(filePath);
	if (!out.is_open()) {
		throw std::runtime_error("Failed to open output file: " + filePath);
	}

	out << "x,y\n";
	out << std::fixed << std::setprecision(9);
	for (const Point& p : points) {
		out << p.x << ',' << p.y << '\n';
	}
}

static std::vector<std::vector<int>> buildNearestNeighbors(const std::vector<Point>& points, int maxNeighbors, double maxDistance) {
	const int n = static_cast<int>(points.size());
	std::vector<std::vector<int>> neighbors(n);

	for (int i = 0; i < n; ++i) {
		std::vector<std::pair<double, int>> dists;
		dists.reserve(n - 1);
		for (int j = 0; j < n; ++j) {
			if (i == j) {
				continue;
			}
			const double d = dist(points[i], points[j]);
			if (d <= maxDistance) {
				dists.push_back({d, j});
			}
		}
		std::sort(dists.begin(), dists.end(), [](const auto& a, const auto& b) {
			return a.first < b.first;
		});
		const int take = std::min(maxNeighbors, static_cast<int>(dists.size()));
		neighbors[i].reserve(take);
		for (int k = 0; k < take; ++k) {
			neighbors[i].push_back(dists[k].second);
		}
	}
	return neighbors;
}

static std::vector<Point> estimateTangents(const std::vector<Point>& cones, const std::vector<std::vector<int>>& neighbors) {
	const int n = static_cast<int>(cones.size());
	std::vector<Point> tangents(n, {1.0, 0.0});

	for (int i = 0; i < n; ++i) {
		if (neighbors[i].empty()) {
			continue;
		}

		double cxx = 0.0;
		double cxy = 0.0;
		double cyy = 0.0;
		int count = 0;

		for (int j : neighbors[i]) {
			const Point d = cones[j] - cones[i];
			cxx += d.x * d.x;
			cxy += d.x * d.y;
			cyy += d.y * d.y;
			++count;
		}

		if (count == 0) {
			continue;
		}

		cxx /= count;
		cxy /= count;
		cyy /= count;

		const double angle = 0.5 * std::atan2(2.0 * cxy, cxx - cyy);
		tangents[i] = {std::cos(angle), std::sin(angle)};
	}

	return tangents;
}

static std::vector<MidpointCandidate> generateMidpointCandidates(const std::vector<Point>& cones, const std::vector<Point>& tangents) {
	const int n = static_cast<int>(cones.size());
	std::vector<MidpointCandidate> mids;
	mids.reserve(n * 4);

	for (int i = 0; i < n; ++i) {
		for (int j = i + 1; j < n; ++j) {
			const double d = dist(cones[i], cones[j]);
			if (d < 2.8 || d > 12.0) {
				continue;
			}

			const Point across = normalize(cones[j] - cones[i]);
			const double parallel = std::abs(dot(tangents[i], tangents[j]));
			const double perpI = 1.0 - std::abs(dot(tangents[i], across));
			const double perpJ = 1.0 - std::abs(dot(tangents[j], across));

			if (parallel < 0.45 || perpI < 0.35 || perpJ < 0.35) {
				continue;
			}

			const double score = parallel + perpI + perpJ - 0.025 * d;
			const Point m = (cones[i] + cones[j]) * 0.5;
			mids.push_back({m, score, i, j});
		}
	}

	return mids;
}

static Point waypointTangent(const std::vector<Point>& path, size_t idx) {
	const size_t n = path.size();
	if (n < 3) {
		return {1.0, 0.0};
	}
	const Point& prev = path[(idx + n - 1) % n];
	const Point& next = path[(idx + 1) % n];
	return normalize(next - prev);
}

static std::vector<Point> refineWaypointsTowardMidline(
	const std::vector<Point>& waypoints,
	const std::vector<MidpointCandidate>& mids,
	const std::vector<Point>& cones,
	double searchRadius,
	double blend
) {
	if (waypoints.empty() || mids.empty()) {
		return waypoints;
	}

	std::vector<Point> refined = waypoints;
	for (int pass = 0; pass < 3; ++pass) {
		std::vector<Point> next = refined;
		for (size_t wi = 0; wi < refined.size(); ++wi) {
			const Point& w = refined[wi];
			const Point tangent = waypointTangent(refined, wi);

			int bestIdx = -1;
			double bestCost = std::numeric_limits<double>::max();

			for (size_t mi = 0; mi < mids.size(); ++mi) {
				const auto& m = mids[mi];
				const double dMid = dist(w, m.p);
				if (dMid > searchRadius) {
					continue;
				}

				if (m.coneA < 0 || m.coneB < 0 || m.coneA >= static_cast<int>(cones.size()) || m.coneB >= static_cast<int>(cones.size())) {
					continue;
				}

				const Point across = normalize(cones[m.coneB] - cones[m.coneA]);
				const double tangentAcross = std::abs(dot(tangent, across));

				const Point va = cones[m.coneA] - w;
				const Point vb = cones[m.coneB] - w;
				const double sideA = cross(tangent, va);
				const double sideB = cross(tangent, vb);
				if (sideA * sideB >= 0.0) {
					continue;
				}

				const double da = norm(va);
				const double db = norm(vb);
				const double symmetry = std::abs(da - db) / std::max(1e-6, da + db);

				// Lower cost is better: near midpoint, across-track pair perpendicular to tangent,
				// and waypoint roughly centered between paired cones.
				double cost = 0.95 * dMid + 1.5 * tangentAcross + 1.2 * symmetry - 0.12 * m.score;
				if (cost < bestCost) {
					bestCost = cost;
					bestIdx = static_cast<int>(mi);
				}
			}

			if (bestIdx >= 0) {
				const Point target = mids[bestIdx].p;
				Point moved = w * (1.0 - blend) + target * blend;

				// Prevent sudden jumps to wrong local branches when track sections are close.
				const Point delta = moved - w;
				const double maxShift = 0.22;
				const double d = norm(delta);
				if (d > maxShift) {
					moved = w + delta * (maxShift / d);
				}
				next[wi] = moved;
			}
		}

		// Light cyclic filter for continuity after each midpoint-attraction pass.
		const size_t n = next.size();
		for (size_t i = 0; i < n; ++i) {
			const Point& prev = next[(i + n - 1) % n];
			const Point& cur = next[i];
			const Point& nxt = next[(i + 1) % n];
			refined[i] = prev * 0.15 + cur * 0.7 + nxt * 0.15;
		}
	}

	return refined;
}

static std::vector<MidpointCandidate> deduplicateMidpoints(const std::vector<MidpointCandidate>& mids, double cellSize) {
	std::unordered_map<std::string, MidpointCandidate> bestByCell;
	bestByCell.reserve(mids.size());

	for (const auto& m : mids) {
		const int gx = static_cast<int>(std::floor(m.p.x / cellSize));
		const int gy = static_cast<int>(std::floor(m.p.y / cellSize));
		const std::string key = std::to_string(gx) + ":" + std::to_string(gy);

		auto it = bestByCell.find(key);
		if (it == bestByCell.end() || m.score > it->second.score) {
			bestByCell[key] = m;
		}
	}

	std::vector<MidpointCandidate> dedup;
	dedup.reserve(bestByCell.size());
	for (const auto& kv : bestByCell) {
		dedup.push_back(kv.second);
	}
	return dedup;
}

static std::vector<MidpointCandidate> densityFilter(const std::vector<MidpointCandidate>& mids, double radius, int minNeighbors) {
	std::vector<MidpointCandidate> filtered;
	filtered.reserve(mids.size());

	for (size_t i = 0; i < mids.size(); ++i) {
		int count = 0;
		for (size_t j = 0; j < mids.size(); ++j) {
			if (i == j) {
				continue;
			}
			if (dist(mids[i].p, mids[j].p) <= radius) {
				++count;
			}
		}
		if (count >= minNeighbors) {
			filtered.push_back(mids[i]);
		}
	}

	return filtered;
}

static bool wouldSelfIntersect(const std::vector<int>& path, int newIndex, const std::vector<Point>& points) {
	if (path.size() < 3) {
		return false;
	}

	const int a = path[path.size() - 1];
	const int b = newIndex;

	for (size_t i = 1; i + 1 < path.size(); ++i) {
		const int c = path[i - 1];
		const int d = path[i];

		if (c == a || d == a || c == b || d == b) {
			continue;
		}

		if (segmentsIntersect(points[a], points[b], points[c], points[d])) {
			return true;
		}
	}
	return false;
}

static std::vector<Point> angleSortFallback(const std::vector<Point>& points) {
	Point centroid{0.0, 0.0};
	for (const auto& p : points) {
		centroid = centroid + p;
	}
	centroid = centroid / static_cast<double>(points.size());

	std::vector<Point> sorted = points;
	std::sort(sorted.begin(), sorted.end(), [&](const Point& a, const Point& b) {
		const double aa = std::atan2(a.y - centroid.y, a.x - centroid.x);
		const double bb = std::atan2(b.y - centroid.y, b.x - centroid.x);
		return aa < bb;
	});
	return sorted;
}

static double closedPathLength(const std::vector<Point>& path) {
	if (path.size() < 2) {
		return 0.0;
	}
	double total = 0.0;
	for (size_t i = 1; i < path.size(); ++i) {
		total += dist(path[i - 1], path[i]);
	}
	total += dist(path.back(), path.front());
	return total;
}

static std::vector<Point> nearestNeighborTourFallback(const std::vector<Point>& points) {
	if (points.size() < 3) {
		return points;
	}

	const int n = static_cast<int>(points.size());
	std::vector<int> order;
	order.reserve(n);
	std::vector<bool> used(n, false);

	int start = 0;
	double bestOriginDist = std::numeric_limits<double>::max();
	for (int i = 0; i < n; ++i) {
		const double d = std::sqrt(points[i].x * points[i].x + points[i].y * points[i].y);
		if (d < bestOriginDist) {
			bestOriginDist = d;
			start = i;
		}
	}

	order.push_back(start);
	used[start] = true;
	while (static_cast<int>(order.size()) < n) {
		const int cur = order.back();
		int next = -1;
		double bestD = std::numeric_limits<double>::max();
		for (int i = 0; i < n; ++i) {
			if (used[i]) {
				continue;
			}
			const double d = dist(points[cur], points[i]);
			if (d < bestD) {
				bestD = d;
				next = i;
			}
		}
		if (next < 0) {
			break;
		}
		order.push_back(next);
		used[next] = true;
	}

	// 2-opt style untangling for a cleaner cyclic route.
	bool improved = true;
	int guard = 0;
	while (improved && guard < 10) {
		improved = false;
		++guard;
		for (int i = 0; i + 3 < n; ++i) {
			for (int j = i + 2; j + 1 < n; ++j) {
				const Point& a = points[order[i]];
				const Point& b = points[order[i + 1]];
				const Point& c = points[order[j]];
				const Point& d = points[order[j + 1]];
				const double before = dist(a, b) + dist(c, d);
				const double after = dist(a, c) + dist(b, d);
				if (after + 1e-9 < before) {
					std::reverse(order.begin() + i + 1, order.begin() + j + 1);
					improved = true;
				}
			}
		}
	}

	std::vector<Point> out;
	out.reserve(order.size());
	for (int idx : order) {
		out.push_back(points[idx]);
	}
	return out;
}

static std::vector<Point> orderCenterline(const std::vector<Point>& points) {
	if (points.size() < 10) {
		return points;
	}

	auto neighbors = buildNearestNeighbors(points, 14, 3.5);

	int start = 0;
	double bestOriginDist = std::numeric_limits<double>::max();
	for (int i = 0; i < static_cast<int>(points.size()); ++i) {
		const double d = std::sqrt(points[i].x * points[i].x + points[i].y * points[i].y);
		if (d < bestOriginDist) {
			bestOriginDist = d;
			start = i;
		}
	}

	std::vector<int> bestPath;

	const int secondOptions = std::min(6, static_cast<int>(neighbors[start].size()));
	for (int option = 0; option < secondOptions; ++option) {
		const int second = neighbors[start][option];
		std::vector<int> path{start, second};
		std::vector<bool> visited(points.size(), false);
		visited[start] = true;
		visited[second] = true;

		bool closed = false;
		for (int iter = 0; iter < static_cast<int>(points.size()) * 3; ++iter) {
			const int prev = path[path.size() - 2];
			const int curr = path.back();

			int bestNext = -1;
			double bestCost = std::numeric_limits<double>::max();
			const Point prevDir = normalize(points[curr] - points[prev]);

			for (int cand : neighbors[curr]) {
				if (cand == prev) {
					continue;
				}

				const bool closing = (cand == start && path.size() > 20);
				if (!closing && visited[cand]) {
					continue;
				}

				const Point nextDir = normalize(points[cand] - points[curr]);
				const double turnCost = 1.0 - std::max(-1.0, std::min(1.0, dot(prevDir, nextDir)));
				const double lenCost = dist(points[curr], points[cand]) * 0.12;
				double cost = turnCost + lenCost;

				if (wouldSelfIntersect(path, cand, points)) {
					cost += 1000.0;
				}

				if (closing) {
					cost -= 0.2;
				}

				if (cost < bestCost) {
					bestCost = cost;
					bestNext = cand;
				}
			}

			if (bestNext < 0 || bestCost > 500.0) {
				break;
			}

			if (bestNext == start) {
				closed = true;
				break;
			}

			path.push_back(bestNext);
			visited[bestNext] = true;
		}

		if (closed && path.size() > bestPath.size()) {
			bestPath = path;
		}
	}

	if (bestPath.size() < 20) {
		return nearestNeighborTourFallback(points);
	}

	std::vector<Point> ordered;
	ordered.reserve(bestPath.size());
	for (int idx : bestPath) {
		ordered.push_back(points[idx]);
	}

	double minX = std::numeric_limits<double>::max();
	double minY = std::numeric_limits<double>::max();
	double maxX = -std::numeric_limits<double>::max();
	double maxY = -std::numeric_limits<double>::max();
	for (const auto& p : ordered) {
		minX = std::min(minX, p.x);
		minY = std::min(minY, p.y);
		maxX = std::max(maxX, p.x);
		maxY = std::max(maxY, p.y);
	}
	const double bboxPerimeter = 2.0 * ((maxX - minX) + (maxY - minY));
	const double routeLen = closedPathLength(ordered);
	if (bboxPerimeter > 1e-6 && routeLen > bboxPerimeter * 6.0) {
		return nearestNeighborTourFallback(points);
	}

	return ordered;
}

static std::vector<Point> resampleClosedPath(const std::vector<Point>& path, double maxSpacing) {
	if (path.size() < 3) {
		return path;
	}

	std::vector<Point> closed = path;
	closed.push_back(path.front());

	std::vector<double> cumulative(closed.size(), 0.0);
	for (size_t i = 1; i < closed.size(); ++i) {
		cumulative[i] = cumulative[i - 1] + dist(closed[i - 1], closed[i]);
	}

	const double totalLength = cumulative.back();
	if (totalLength < 1e-6) {
		return path;
	}

	const int sampleCount = std::max(20, static_cast<int>(std::ceil(totalLength / maxSpacing)));
	std::vector<Point> out;
	out.reserve(sampleCount);

	for (int s = 0; s < sampleCount; ++s) {
		const double target = totalLength * static_cast<double>(s) / static_cast<double>(sampleCount);
		auto it = std::lower_bound(cumulative.begin(), cumulative.end(), target);
		size_t idx = static_cast<size_t>(std::distance(cumulative.begin(), it));
		if (idx == 0) {
			out.push_back(closed[0]);
			continue;
		}
		if (idx >= closed.size()) {
			out.push_back(closed.back());
			continue;
		}

		const double l0 = cumulative[idx - 1];
		const double l1 = cumulative[idx];
		const double t = (l1 - l0 > 1e-9) ? (target - l0) / (l1 - l0) : 0.0;
		out.push_back(closed[idx - 1] * (1.0 - t) + closed[idx] * t);
	}

	return out;
}

static std::vector<Point> smoothClosedPath(std::vector<Point> path, int iterations, double alpha) {
	if (path.size() < 5) {
		return path;
	}

	const size_t n = path.size();
	for (int it = 0; it < iterations; ++it) {
		std::vector<Point> next = path;
		for (size_t i = 0; i < n; ++i) {
			const Point& prev = path[(i + n - 1) % n];
			const Point& cur = path[i];
			const Point& nxt = path[(i + 1) % n];
			const Point lap = (prev + nxt) * 0.5 - cur;
			next[i] = cur + lap * alpha;
		}
		path.swap(next);
	}
	return path;
}

static std::vector<Point> decimateClosedPath(const std::vector<Point>& path, double minSpacing) {
	if (path.size() < 4) {
		return path;
	}

	std::vector<Point> out;
	out.reserve(path.size());
	out.push_back(path.front());

	Point last = path.front();
	for (size_t i = 1; i < path.size(); ++i) {
		if (dist(last, path[i]) >= minSpacing) {
			out.push_back(path[i]);
			last = path[i];
		}
	}

	if (out.size() < 3) {
		return path;
	}
	return out;
}

int main(int argc, char** argv) {
	try {
		const std::string inputPath = (argc > 1) ? argv[1] : "Q3/track1.csv";
		const std::string outputPath = (argc > 2) ? argv[2] : "Q3/waypoints_generated.csv";

		const std::vector<Point> cones = readCsv(inputPath);
		if (cones.size() < 26 || cones.size() > 300) {
			std::cerr << "Unexpected cone count: " << cones.size() << " (expected 26..300)\n";
			return 1;
		}

		const auto coneNeighbors = buildNearestNeighbors(cones, 8, 6.0);
		const auto tangents = estimateTangents(cones, coneNeighbors);

		auto mids = generateMidpointCandidates(cones, tangents);
		mids = deduplicateMidpoints(mids, 0.5);
		mids = densityFilter(mids, 2.0, 2);

		std::sort(mids.begin(), mids.end(), [](const MidpointCandidate& a, const MidpointCandidate& b) {
			return a.score > b.score;
		});
		const size_t keepCount = std::min(mids.size(), static_cast<size_t>(std::max<size_t>(180, cones.size() * 3)));
		mids.resize(keepCount);

		if (mids.size() < 15) {
			std::cerr << "Failed to derive enough midpoint candidates.\n";
			return 1;
		}

		std::vector<Point> midpointCloud;
		midpointCloud.reserve(mids.size());
		for (const auto& m : mids) {
			midpointCloud.push_back(m.p);
		}

		auto orderedCenterline = orderCenterline(midpointCloud);
		orderedCenterline = smoothClosedPath(orderedCenterline, 3, 0.2);
		orderedCenterline = decimateClosedPath(orderedCenterline, 0.35);
		auto waypoints = resampleClosedPath(orderedCenterline, 0.5);
		waypoints = refineWaypointsTowardMidline(waypoints, mids, cones, 2.7, 0.45);
		waypoints = smoothClosedPath(waypoints, 2, 0.12);
		waypoints = resampleClosedPath(waypoints, 0.5);

		if (waypoints.size() < 20) {
			std::cerr << "Generated too few waypoints.\n";
			return 1;
		}

		writeCsv(outputPath, waypoints);
		std::cout << "Generated " << waypoints.size() << " waypoints -> " << outputPath << '\n';
		return 0;
	} catch (const std::exception& e) {
		std::cerr << "Error: " << e.what() << '\n';
		return 1;
	}
}

